### ISSUE TITLE
Project is slow to clone because it contains checked-in dune binaries

### ISSUE THREAD

**Issue by gridbugs** [tarides/dune-binary-distribution#11]
These make the repo really big. It would be better if the binaries were stored elsewhere, especially since they are no longer used. Unfortunately this can't be fixed by just commiting to this repo as the binaries will always be in the commit history. The only way to remove them will be to rewrite history such that they were never checked-in and then force push to the main branch.

**Comment by maiste** [comment]
It would require a `git push --force` on `main`. Good catch! We should definitely consider this as soon as possible to avoid the repository being larger.

**Comment by maiste** [comment]
Done  :white_check_mark:
